version: "3"
services:
  postgres:
    image: postgres:12.3
    ports:
      - "32532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2.cli-migrations-v2
    ports:
      - "32533:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - ./hasura/.env
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
volumes:
  db_data:
